In [1]:
import pandas as pd
import numpy as np

In [2]:
panel1 = pd.read_csv('../data/cleaned/panel_migration.csv')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_25900\369774472.py:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  panel1 = pd.read_csv('../data/cleaned/panel_migration.csv')

In [3]:
net = pd.read_csv('../data/cleaned/network_variables.csv')

In [4]:
print(net[(net["year"] == 1990) & (net["alpha"] == 0.8)]["in_cp"].value_counts())
print(net[(net["year"] == 2000) & (net["alpha"] == 0.8)]["in_cp"].value_counts())
print(net[(net["year"] == 2010) & (net["alpha"] == 0.8)]["in_cp"].value_counts())
print(net[(net["year"] == 2020) & (net["alpha"] == 0.8)]["in_cp"].value_counts())

in_cp
0    199
1      4
Name: count, dtype: int64
in_cp
0    196
1      8
Name: count, dtype: int64
in_cp
0    192
1     13
Name: count, dtype: int64
in_cp
0    190
1     14
Name: count, dtype: int64

In [5]:
print(net.shape)
print(panel1.shape)

(25328, 27)
(1296420, 75)

In [6]:
print(panel1['dyad_id'].nunique())
print(panel1['origin'].nunique())
print(panel1['destination'].nunique())
print(net['country'].nunique())

41820
205
205
205

In [7]:
net.columns

Index(['Unnamed: 0', 'country', 'alpha', 'out_deg', 'in_deg', 'year', 'id',
       'sigma_in', 'sigma_out', 'sigma_all', 'RANK', 'RANKout', 'RANKin',
       'in_cp', 'out_cp', 'all_cp', 'median_sigma_in', 'median_sigma_out',
       'core_3', 'core_4', 'log_in_deg', 'log_out_deg', 'q75_in', 'q75_out',
       'med_in_deg', 'med_out_deg', 'type_hybrid'],
      dtype='object')

In [8]:
net = net.drop(columns = ['Unnamed: 0'])

In [9]:
origin = net.copy()

In [10]:
origin.head(2)

,country,alpha,out_deg,in_deg,year,id,sigma_in,sigma_out,sigma_all,RANK,...,median_sigma_out,core_3,core_4,log_in_deg,log_out_deg,q75_in,q75_out,med_in_deg,med_out_deg,type_hybrid
0,Afghanistan,0.0,105.000000,107.000000,1990,Afghanistan,91811,19069,110880,2,...,142838.0,2,pure_magnet,4.682131,4.663439,181119.0,307768.0,1090.346193,1363.451306,periphery
1,Afghanistan,0.5,2789.923025,317.965908,1990,Afghanistan,91811,19069,110880,2,...,142838.0,2,pure_magnet,5.765084,7.934128,181119.0,307768.0,1090.346193,1363.451306,periphery

In [11]:
destination = net.copy()

In [12]:
destination_metrices = {'country': 'destination', 'out_deg': 'out_deg_d', 'in_deg': 'in_deg_d', 'sigma_in': 'sigma_in_d','sigma_out': 'sigma_out_d',
                        'sigma_all': 'sigma_all_d', 'RANK': 'RANK_d', 'RANKin': 'RANKin_d','RANKout': 'RANKout_d','in_cp': 'in_cp_d','out_cp': 'out_cp_d', 
                        'all_cp': 'all_cp_d', 'median_sigma_in': 'median_sigma_in_d', 'median_sigma_out': 'median_sigma_out_d','core_3': 'core_3_d',
                        'core_4': 'core_4_d','log_in_deg': 'log_in_deg_d', 'log_out_deg': 'log_out_deg_d', 'q75_in': 'q75_in_d','q75_out': 'q75_out_d', 
                        'low_node': 'low_node_d', 'type_hybrid' : 'type_hybrid_d', 'q05_in': 'q05_in_d', 'q05_out': 'q05_out_d', 'med_in_deg':'med_in_deg_d',
                        'med_out_deg': 'med_out_deg_d'}

In [13]:
destination = destination.rename(columns = destination_metrices)

In [14]:
origin = origin.rename(columns = {"country": "origin"})

In [15]:
origin.columns

Index(['origin', 'alpha', 'out_deg', 'in_deg', 'year', 'id', 'sigma_in',
       'sigma_out', 'sigma_all', 'RANK', 'RANKout', 'RANKin', 'in_cp',
       'out_cp', 'all_cp', 'median_sigma_in', 'median_sigma_out', 'core_3',
       'core_4', 'log_in_deg', 'log_out_deg', 'q75_in', 'q75_out',
       'med_in_deg', 'med_out_deg', 'type_hybrid'],
      dtype='object')

In [16]:
destination.columns

Index(['destination', 'alpha', 'out_deg_d', 'in_deg_d', 'year', 'id',
       'sigma_in_d', 'sigma_out_d', 'sigma_all_d', 'RANK_d', 'RANKout_d',
       'RANKin_d', 'in_cp_d', 'out_cp_d', 'all_cp_d', 'median_sigma_in_d',
       'median_sigma_out_d', 'core_3_d', 'core_4_d', 'log_in_deg_d',
       'log_out_deg_d', 'q75_in_d', 'q75_out_d', 'med_in_deg_d',
       'med_out_deg_d', 'type_hybrid_d'],
      dtype='object')

In [17]:
destination = destination.drop(columns = ['id'])

In [18]:
panel2 = panel1.merge(origin, on = ['origin', 'year'], how = 'left')

In [19]:
panel2.shape

(5171604, 99)

In [20]:
205*204

41820

In [21]:
41820*4*31

5185680

In [22]:
print(panel1['origin'].nunique())
print(panel2['origin'].nunique())
print(panel1['destination'].nunique())
print(panel2['destination'].nunique())
print(panel2['alpha'].nunique())

205
205
205
205
4

In [23]:
print(panel2[(panel2['origin'] == "Bangladesh") & (panel2['year'] == 1990) & (panel2['alpha'] == 0)].shape)
print(panel2[(panel2['origin'] == "Bangladesh") & (panel2['year'] == 1990) & (panel2['alpha'] == 0.5)].shape)
print(panel2[(panel2['origin'] == "Bangladesh") & (panel2['year'] == 1990) & (panel2['alpha'] == 0.8)].shape)
print(panel2[(panel2['origin'] == "Bangladesh") & (panel2['year'] == 1990) & (panel2['alpha'] == 1)].shape)

(204, 99)
(204, 99)
(204, 99)
(204, 99)

In [24]:
panel2[(panel2['year'] == 1990) & (panel2['alpha'] == 0)]['origin'].nunique()

203

In [25]:
set(panel2[(panel2['year'] == 1990) & (panel2['alpha'] == 0.8)]['destination'].unique()) - set(panel2[(panel2['year'] == 1990) & (panel2['alpha'] == 0.8)]['origin'].unique())

{'Kosovo', 'Yemen, Rep.'}

In [26]:
set(panel2[(panel2['year'] == 2009) & (panel2['alpha'] == 0.8)]['destination'].unique()) - set(panel2[(panel2['year'] == 2009) & (panel2['alpha'] == 0.8)]['origin'].unique())

{'Kosovo'}

In [27]:
set(panel2[(panel2['year'] == 2010) & (panel2['alpha'] == 0.8)]['destination'].unique()) - set(panel2[(panel2['year'] == 2010) & (panel2['alpha'] == 0.8)]['origin'].unique())

set()

In [28]:
set(panel2[(panel2['year'] == 2019) & (panel2['alpha'] == 0.8)]['destination'].unique()) - set(panel2[(panel2['year'] == 2019) & (panel2['alpha'] == 0.8)]['origin'].unique())

{'Kosovo'}

In [29]:
panel2[(panel2['year'] == 2020) & (panel2['alpha'] == 0.8) & (panel2['destination'] == 'Yemen, Rep.')].head()

,origin,destination,year,stock,flow,iso_o,region,region_d,GDP_pc,GDP_pc_d,...,median_sigma_out,core_3,core_4,log_in_deg,log_out_deg,q75_in,q75_out,med_in_deg,med_out_deg,type_hybrid
5006726,Zambia,"Yemen, Rep.",2020,NaN,NaN,ZMB,NaN,NaN,1228.735,NaN,...,293242.5,2.0,pure_magnet,9.621404,9.766093,312855.75,686041.75,1537.253462,1921.410887,periphery
5006978,Zimbabwe,"Yemen, Rep.",2020,NaN,NaN,ZWE,NaN,NaN,1230.819,NaN,...,293242.5,2.0,pure_magnet,10.087569,11.227087,312855.75,686041.75,1537.253462,1921.410887,periphery
5007370,Virgin Islands (U.S.),"Yemen, Rep.",2020,NaN,NaN,VIR,NaN,NaN,35850.743,NaN,...,293242.5,3.0,periphery,8.677479,6.529152,312855.75,686041.75,1537.253462,1921.410887,periphery
5007746,Venezuela,"Yemen, Rep.",2020,NaN,NaN,VEN,NaN,NaN,1255.373,NaN,...,293242.5,2.0,pure_magnet,11.277583,12.403681,312855.75,686041.75,1537.253462,1921.410887,pure_magnet
5008314,Samoa,"Yemen, Rep.",2020,NaN,NaN,WSM,NaN,NaN,4283.064,NaN,...,293242.5,3.0,periphery,6.521997,9.453578,312855.75,686041.75,1537.253462,1921.410887,periphery

In [30]:
a = ['Kosovo', 'Yemen, Rep.']

In [31]:
panel3 = panel2[~panel2['origin'].isin(a) & ~panel2['destination'].isin(a)]

In [32]:
print(panel2['origin'].nunique())
print(panel2['destination'].nunique())
print(panel3['origin'].nunique())
print(panel3['destination'].nunique())

205
205
203
203

In [33]:
# This removes the alpha filter to show the 'hidden' row
print(panel3[(panel3['origin'] == "Bangladesh") & (panel3['year'] == 1990)].shape)

(808, 99)

In [34]:
panel3.columns

Index(['origin', 'destination', 'year', 'stock', 'flow', 'iso_o', 'region',
       'region_d', 'GDP_pc', 'GDP_pc_d', 'mortality', 'mortality_d',
       'primary_enroll', 'secondary_enroll', 'secondary_enroll_d',
       'tertiary_enroll', 'tertiary_enroll_d', 'maternal_death_risk',
       'maternal_death_risk_d', 'mmr', 'mmr_d', 'primary_enroll_d',
       'literacy_rate', 'literacy_rate_d', 'gini', 'gini_d',
       'electoral_dem_index', 'electoral_dem_index_d', 'nourishment',
       'nourishment_d', 'government_effec_index', 'government_effec_index_d',
       'political_corruption_index', 'political_corruption_index_d', 'gii',
       'gii_d', 'lfp_f', 'lfp_f_d', 'parliament_seat_f', 'parliament_seat_f_d',
       'hdi', 'hdi_d', 'life_exp', 'life_exp_d', 'mean_schooling',
       'mean_schooling_d', 'coef_human_inequality', 'coef_human_inequality_d',
       'inequality_edu', 'inequality_edu_d', 'inequality_income',
       'inequality_income_d', 'inequality_le', 'inequality_le_d', 'idealpoint',
       'idealpoint_d', 'DPT_immunization', 'DPT_immunization_d',
       'population_growth', 'population_growth_d', 'session_x',
       'infant_survival', 'infant_survival_d', 'maternal_survival',
       'maternal_survival_d', 'lfp', 'lfp_d', 'hci', 'hci_d', 'employment',
       'employment_d', 'undernourishment', 'undernourishment_d', 'dyad_id',
       'pair', 'alpha', 'out_deg', 'in_deg', 'id', 'sigma_in', 'sigma_out',
       'sigma_all', 'RANK', 'RANKout', 'RANKin', 'in_cp', 'out_cp', 'all_cp',
       'median_sigma_in', 'median_sigma_out', 'core_3', 'core_4', 'log_in_deg',
       'log_out_deg', 'q75_in', 'q75_out', 'med_in_deg', 'med_out_deg',
       'type_hybrid'],
      dtype='object')

In [35]:
panel2.shape

(5171604, 99)

In [36]:
destination.shape

(25328, 25)

In [37]:
panel4 = panel3.merge(destination, on = ['destination', 'year', 'alpha'], how = 'left')

In [38]:
panel4.shape

(5084744, 121)

In [39]:
len(list(panel4.columns))

121

In [40]:
panel4['dyad_id'].head()

0    Antigua and Barbuda-Aruba
1    Antigua and Barbuda-Aruba
2    Antigua and Barbuda-Aruba
3    Antigua and Barbuda-Aruba
4                Niger-Hungary
Name: dyad_id, dtype: object

In [41]:
# Keeping one alpha value for now. Will change if needed
panel4 = panel4[panel4['alpha'] == 0.8]

In [43]:
panel4["corridor"] = np.nan
panel4.loc[(panel4["in_cp"] == 0.0) & (panel4["in_cp_d"] == 0), "corridor"] = 1
panel4.loc[(panel4["in_cp"] == 1.0) & (panel4["in_cp_d"] == 0), "corridor"] = 2
panel4.loc[(panel4["in_cp"] == 0.0) & (panel4["in_cp_d"] == 1), "corridor"] = 3
panel4.loc[(panel4["in_cp"] == 1.0) & (panel4["in_cp_d"] == 1), "corridor"] = 4

In [44]:
panel4[["corridor", "in_cp", "in_cp_d", "alpha"]].head()

    corridor  in_cp  in_cp_d  alpha
2        1.0    0.0        0    0.8
6        1.0    0.0        0    0.8
10       1.0    0.0        0    0.8
14       1.0    0.0        0    0.8
18       3.0    0.0        1    0.8

In [45]:
panel4.to_csv('../data/cleaned/panel_migration.csv', encoding = 'utf-8', index = False)

# tables

In [46]:
panel4 = pd.read_csv('../data/cleaned/panel_migration.csv')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_25900\3715062751.py:1: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  panel4 = pd.read_csv('../data/cleaned/panel_migration.csv')

In [47]:
countries = list(panel4[panel4['year'] == 1990]['origin'].unique())

In [48]:
c = pd.DataFrame(countries, columns=['countries'])
c.to_csv('../data/cleaned/country_list.csv', index=False)

In [49]:
panel4[panel4['in_cp'] == 1]['origin'].unique()

array(['Russian Federation', 'India', 'Ukraine',
       'United States of America', 'Germany', 'France', 'Canada',
       'Saudi Arabia', 'United Kingdom', 'Australia',
       'United Arab Emirates', 'Spain', 'Italy', 'Turkey'], dtype=object)

In [50]:
core_table = (panel4.loc[panel4['in_cp'] == 1].groupby('origin').agg(first_core_year = ('year', 'min'), last_core_year=('year', 'max'),
years_as_core=('year', 'nunique')).reset_index().sort_values('first_core_year'))
core_table = core_table.reset_index(drop = True)
#in_cp identifies countries that are central in terms of incoming migration ties.

In [51]:
core_table

                      origin  first_core_year  last_core_year  years_as_core
0                      India             1990            2020             31
1         Russian Federation             1990            2020             31
2                    Ukraine             1990            2020             31
3   United States of America             1990            2020             31
4                    Germany             1992            2020             29
5                     France             1993            2020             28
6                     Canada             1999            2020             22
7               Saudi Arabia             1999            2020             22
8             United Kingdom             2002            2020             19
9                  Australia             2005            2020             16
10                     Italy             2007            2020             14
11                     Spain             2007            2020             14
12      United Arab Emirates             2007            2020             14
13                    Turkey             2016            2020              5

In [52]:
core_table.to_csv('../data/cleaned/cores.csv', index=False)